### ISSUE TITLE
The link to templates in the main page is broken.

### ISSUE THREAD

**Issue by sangwon-hyun** [jacobbien/litr-project#33]
This link is broken, in the main page: [template](https://github.com/jacobbien/litr-project/blob/main/litr/articles/package-templates.html).

**Comment by jacobbien** [comment]
Oh interesting.  It works from [here](https://jacobbien.github.io/litr-project/) but not from [here](https://github.com/jacobbien/litr-project/tree/main/litr/).  The reason being that I was using relative paths.  Thanks for pointing this out.

**Comment by jacobbien** [comment]
Closed by e0c3662a92722c3e81a9d7bcae7602a6aa58faa7
