### ISSUE TITLE
Suggest developers use Github PAT when developing litr to avoid rate limiting 

### ISSUE THREAD

**Issue by patrickvossler18** [jacobbien/litr-project#39]
It is pretty easy to get rate limited by github when building litr on a machine that doesn't have a github PAT. It might be useful to add a recommendation to add a github PAT to your `.Renviron` file  if you want to work on developing litr. 

Here's my suggestion that is based on the error message from the `remotes` package

> Knitting `create-litr.Rmd` makes quite a few calls to the GitHub API and it is easy to quickly reach the GitHub rate limit knitting `create-litr.Rmd` repeatedly in a short period of time. To increase your GitHub API rate limit
> - Use `usethis::create_github_token()` to create a Personal Access Token.
> - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

Perhaps we could put this message in `CONTRIBUTING` in the root of the directory?

**Comment by jacobbien** [comment]
Closed by #40
