### ISSUE TITLE
} missing in R package with data

### ISSUE THREAD

**Issue by xyzyc** [jacobbien/litr-project#44]
In https://github.com/jacobbien/litr-project/blob/main/source-files/make-an-r-package-with-data/skeleton.Rmd, line 67--73,
you have 
#' A regression data set
#' 
#' @format A data frame with 100 rows and 2 variables:
#' \describe{
#' \item{x}{a predictor variable}
#' \item{y}{a response variable}
#' @source This data was simulated.  But usually we might cite a source here.

I think you are missing a } at the end of describe.
So it should be:
#' A regression data set
#' 
#' @format A data frame with 100 rows and 2 variables:
#' \describe{
#' \item{x}{a predictor variable}
#' \item{y}{a response variable}
#` }
#' @source This data was simulated.  But usually we might cite a source here.

**Comment by jacobbien** [comment]
Thanks!  Commit b7ff068 fixes this.
