### ISSUE TITLE
How can I use RcppArmadillo?

### ISSUE THREAD

**Issue by sangwon-hyun** [jacobbien/litr-project#47]
I see from [templates](https://htmlpreview.github.io/?https://github.com/jacobbien/litr-project/blob/main/examples/make-an-r-package-with-rcpp/create-withrcpp.html) that when I'm looking to use Rcpp, I can use this at the beginning of an Rcpp code block:
```
#include <Rcpp.h>
using namespace Rcpp;
```
What should I do when I'm looking to use libraries like Armadillo or Eigen  (or numeric)? My guess would be to do:
```
#include <numeric>
#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;
using namespace Eigen;
```
But that doesn't work :)

**Comment by sangwon-hyun** [comment]
Ok thank you! 

I'm happy to report that I'm able to use not only RcppArmadillo but also RcppEigen! Like this:

> ```{Rcpp}
> // [[Rcpp::depends(RcppArmadillo)]]
> // [[Rcpp::depends(RcppEigen)]]
> #include <RcppArmadillo.h>
> #include <RcppEigen.h>
> #include <numeric>
> using namespace arma;
> using namespace Eigen;
> 
> using Eigen::Map;                       // 'maps' rather than copies
> using Eigen::MatrixXd;                  // variable size matrix, double precision
> 
> //' Solve "barebones" sylvester equation that takes upper triangular matrices as coefficients.
> //' 
> //' @param TA Upper-triangular matrix
> //' @param TB Upper-triangular matrix
> //' @param C matrix
> //' @export
> // [[Rcpp::export]]
> Eigen::MatrixXd matrix_function_solve_triangular_sylvester_barebonesC2(const Eigen::MatrixXd & TA,
> 								     const Eigen::MatrixXd & TB,
> 								     const Eigen::MatrixXd & C){
>   // Eigen::eigen_assert(TA.rows() == TA.cols());
>   // Eigen::eigen_assert(TA.Eigen::isUpperTriangular());
>   // Eigen::eigen_assert(TB.rows() == TB.cols());
>   // Eigen::eigen_assert(TB.Eigen::isUpperTriangular());
>   // Eigen::eigen_assert(C.rows() == TA.rows());
>   // Eigen::eigen_assert(C.cols() == TB.rows());
> 
>   // typedef typename MatrixType::Index Index;
>   // typedef typename MatrixType::Scalar Scalar;
> 
>   int m = TA.rows();
>   int n = TB.rows();
>   Eigen::MatrixXd X(m, n);
> 
>   for (int i = m - 1; i >= 0; --i) {
>     for (int j = 0; j < n; ++j) {
> 
>       // Compute T_A X = \sum_{k=i+1}^m T_A_{ik} X_{kj}
>       double TAX;
>       if (i == m - 1) {
>       	TAX = 0;
>       } else {
> 	MatrixXd TAXmatrix = TA.row(i).tail(m-1-i) * X.col(j).tail(m-1-i);
>       	TAX = TAXmatrix(0,0);
>       }
> 
>       // Compute X T_B = \sum_{k=1}^{j-1} X_{ik} T_B_{kj}
>       double XTB;
>       if (j == 0) {
>       	XTB = 0;
>       } else {
>       	MatrixXd XTBmatrix = X.row(i).head(j) * TB.col(j).head(j);
>       	XTB = XTBmatrix(0,0);
>       }
> 
>       X(i,j) = (C(i,j) - TAX - XTB) / (TA(i,i) + TB(j,j));
>     }
>   }
>   return X;
> }
> ```

works well! Here's some test code:

> ```{r}
> library(tidyverse)
> set.seed(100)
> A = runif(4) %>% matrix(ncol=2)
> B = runif(4) %>% matrix(ncol=2)
> C = runif(4) %>% matrix(ncol=2)
> A[lower.tri(A)]=0
> B[lower.tri(B)]=0
> C[lower.tri(C)]=0
> a <- matrix_function_solve_triangular_sylvester_barebonesC2(A, B, C)
> a
> ```

I have another simple request! It seems like `litr::document()` is meant to be run at the end of _any_ workflow. However, the current website showcasing the bookdown template doesn't make this clear:
![image](https://user-images.githubusercontent.com/1526679/231901705-fd3a6520-21fb-4f10-9251-03f1544c28f9.png)
and just ends with "etc." instead of showing `5conclude.Rmd`.

(To elaborate, my workflow was to (1) run `litr::render("index.Rmd")` to create a package in `./mypackage`, then (2) run `install.package("mypackage", repos=NULL, type="source")`. All without `litr::document()`. As I started to define Rcpp functions, I'd get the following error during this second step: 
![image](https://user-images.githubusercontent.com/1526679/231902609-b08950bd-f4dd-4185-9ccb-ab9ec84e6284.png)
which, it turns out, [document()](https://github.com/jacobbien/litr-project/blob/3fe3b01c93b49cc1d2264cdcbe9eb379f7d0ec50/create-litr.Rmd#L738) already anticipates! But this error message is not useful for your average litr+bookdown user..)

Here's one simple suggestion: when showcasing templates, instead of ending with "etc.", maybe end with `5conclude.Rmd`? Something like this:

[index.Rmd](https://github.com/jacobbien/litr-project/blob/main/examples/make-an-r-package-from-bookdown/index.Rmd), [1description.Rmd](https://github.com/jacobbien/litr-project/blob/main/examples/make-an-r-package-from-bookdown/1description.Rmd), ⋯, [5conclude.Rmd](https://github.com/jacobbien/litr-project/blob/main/examples/make-an-r-package-from-bookdown/5conclude.Rmd)

Or an alternative is to showcase somewhere that the workflow is incomplete if you _don't_ end with `litr::document()`. Maybe in the FAQ, or at the end of [basic-example.html](https://jacobbien.github.io/litr-project/articles/basic-example.html) ?

**Comment by jacobbien** [comment]
Thanks, a03a34c follows both of these last two suggestions.
